import Container from "@/components/Container";
import FadeIn from "@/components/FadeIn";
import PageIntro from "@/components/PageIntro";
import React from "react";

export const metadata = {
  title: "Privacy Policy",
};

const Section = ({ title, children }) => (
  <div className="mt-10">
    <h2 className="font-display text-xl font-semibold text-foreground">
      {title}
    </h2>
    <div className="mt-4 space-y-4 text-base/7 text-muted-foreground">
      {children}
    </div>
  </div>
);

const PrivacyPolicyPage = () => {
  return (
    <>
      <PageIntro eyebrow="Legal" title="Privacy Policy">
        <p>
          Evergreen Ridge Technologies LLC (&ldquo;Evergreen Ridge
          Technology,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;) respects your privacy. This policy explains what
          information we collect through this website, how we use it, and
          your choices.
        </p>
      </PageIntro>

      <Container className="mt-16 sm:mt-20">
        <FadeIn>
          <div className="rounded-4xl border border-border bg-card p-8 sm:p-10">
            <p className="text-sm text-muted-foreground">
              Effective date: August 1, 2026
            </p>

            <Section title="Information we collect">
              <p>
                We only collect information you choose to give us. That
                happens in two places on this site:
              </p>
              <ul className="list-disc space-y-2 pl-6">
                <li>
                  <strong className="text-foreground">Contact form</strong> —
                  name, email address, company, phone number, and the message
                  you send us.
                </li>
                <li>
                  <strong className="text-foreground">Cost Estimator</strong>{" "}
                  — your name, email address, and the project details you
                  select or type in (project type, features, complexity,
                  timeline, budget range, and any notes), so we can send you a
                  draft estimate and follow up if you&apos;d like to talk
                  further.
                </li>
              </ul>
              <p>
                We do not use cookies or analytics tools to track visitors on
                this site today. If that changes, we will update this policy.
              </p>
            </Section>

            <Section title="How we use your information">
              <p>We use the information you submit to:</p>
              <ul className="list-disc space-y-2 pl-6">
                <li>Respond to your inquiry or message.</li>
                <li>
                  Generate and email you a draft project estimate you
                  requested.
                </li>
                <li>
                  Follow up about a potential project, if you&apos;ve
                  indicated interest.
                </li>
              </ul>
              <p>We do not sell, rent, or trade your personal information.</p>
            </Section>

            <Section title="How your information is shared">
              <p>
                Form and estimator submissions are delivered to us by email
                using{" "}
                <a
                  href="https://www.resend.com"
                  className="text-primary underline"
                  target="_blank"
                  rel="noreferrer"
                >
                  Resend
                </a>
                , a third-party email delivery service that transmits the
                message from your browser to our inbox. Resend processes
                this data solely to deliver the email and does not use it for
                any other purpose on our behalf. We do not share your
                information with any other third party except as required by
                law.
              </p>
            </Section>

            <Section title="Data retention">
              <p>
                We keep the emails generated by the contact form and Cost
                Estimator for as long as reasonably necessary to respond to
                you and maintain business records, after which they may be
                deleted.
              </p>
            </Section>

            <Section title="Children's privacy">
              <p>
                This site is intended for businesses and professionals. We do
                not knowingly collect personal information from children
                under 13.
              </p>
            </Section>

            <Section title="Your rights">
              <p>
                You can ask us to access, correct, or delete the personal
                information you&apos;ve submitted to us by emailing{" "}
                <a
                  href="mailto:contact@evergreenridgetech.com"
                  className="text-primary underline"
                >
                  contact@evergreenridgetech.com
                </a>
                .
              </p>
            </Section>

            <Section title="Changes to this policy">
              <p>
                We may update this policy from time to time. Changes will be
                posted on this page with a new effective date.
              </p>
            </Section>

            <Section title="Contact us">
              <p>
                Questions about this policy? Email{" "}
                <a
                  href="mailto:contact@evergreenridgetech.com"
                  className="text-primary underline"
                >
                  contact@evergreenridgetech.com
                </a>
                .
              </p>
            </Section>
          </div>
        </FadeIn>
      </Container>
    </>
  );
};

export default PrivacyPolicyPage;
