import fs from "fs";
import path from "path";
import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";
import { EstimatePayload } from "../types";
import { formatCurrency } from "../email/templates";

// In production, esbuild bundles everything into a single dist/index.js, so
// __dirname is dist/ and the logo (copied there by the build script) sits at
// dist/assets/logo.png. In dev (tsx, unbundled) __dirname is src/pdf/, and the
// logo lives one level up at src/assets/logo.png. Try the bundled layout first,
// fall back to the unbundled one.
function resolveLogoPath() {
  const bundledPath = path.join(__dirname, "assets", "logo.png");
  if (fs.existsSync(bundledPath)) return bundledPath;
  return path.join(__dirname, "..", "assets", "logo.png");
}

const LOGO_PATH = resolveLogoPath();

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", color: "#121212" },
  logo: { height: 40, marginBottom: 20 },
  title: { fontSize: 18, fontWeight: 700, marginBottom: 4, color: "#0C3428" },
  subtitle: { fontSize: 10, color: "#64748B", marginBottom: 20 },
  summaryRow: { flexDirection: "row", marginBottom: 20 },
  summaryBox: {
    flex: 1,
    backgroundColor: "#E6ECE9",
    borderRadius: 6,
    padding: 10,
    marginRight: 8,
  },
  summaryLabel: { fontSize: 9, color: "#64748B", marginBottom: 4 },
  summaryValue: { fontSize: 13, fontWeight: 700, color: "#0C3428" },
  sectionTitle: { fontSize: 12, fontWeight: 700, marginTop: 16, marginBottom: 8, color: "#0C3428" },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#0C3428",
    color: "#F7F9F8",
    padding: 6,
  },
  tableRow: {
    flexDirection: "row",
    padding: 6,
    borderBottom: "1px solid #E6ECE9",
  },
  colLabel: { flex: 3 },
  colHours: { flex: 1, textAlign: "right" },
  colCost: { flex: 1, textAlign: "right" },
  disclaimer: { marginTop: 24, fontSize: 9, color: "#64748B", lineHeight: 1.4 },
  footer: { marginTop: 24, fontSize: 9, color: "#94A3B8" },
});

const EstimateDocument = ({ estimate }: { estimate: EstimatePayload }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Image src={LOGO_PATH} style={styles.logo} />
      <Text style={styles.title}>Draft Project Estimate</Text>
      <Text style={styles.subtitle}>
        Prepared for {estimate.name} — {estimate.project_type} · {new Date().toLocaleDateString("en-US")}
      </Text>

      <View style={styles.summaryRow}>
        <View style={styles.summaryBox}>
          <Text style={styles.summaryLabel}>Total Hours</Text>
          <Text style={styles.summaryValue}>{estimate.total_hours}</Text>
        </View>
        <View style={styles.summaryBox}>
          <Text style={styles.summaryLabel}>Estimated Cost</Text>
          <Text style={styles.summaryValue}>
            {formatCurrency(estimate.total_low)} – {formatCurrency(estimate.total_high)}
          </Text>
        </View>
        <View style={[styles.summaryBox, { marginRight: 0 }]}>
          <Text style={styles.summaryLabel}>Timeline</Text>
          <Text style={styles.summaryValue}>{estimate.timeline}</Text>
        </View>
      </View>

      <Text style={styles.sectionTitle}>Feature Breakdown</Text>
      <View style={styles.tableHeader}>
        <Text style={styles.colLabel}>Feature</Text>
        <Text style={styles.colHours}>Hours</Text>
        <Text style={styles.colCost}>Cost</Text>
      </View>
      {estimate.breakdown.map((line) => (
        <View style={styles.tableRow} key={line.label}>
          <Text style={styles.colLabel}>{line.label}</Text>
          <Text style={styles.colHours}>{line.hours}</Text>
          <Text style={styles.colCost}>{formatCurrency(line.cost)}</Text>
        </View>
      ))}

      <Text style={styles.sectionTitle}>Project Buffers</Text>
      <View style={styles.tableHeader}>
        <Text style={styles.colLabel}>Item</Text>
        <Text style={styles.colHours}>Hours</Text>
        <Text style={styles.colCost}>Cost</Text>
      </View>
      {estimate.bufferLines.map((line) => (
        <View style={styles.tableRow} key={line.label}>
          <Text style={styles.colLabel}>{line.label}</Text>
          <Text style={styles.colHours}>{line.hours}</Text>
          <Text style={styles.colCost}>{formatCurrency(line.cost)}</Text>
        </View>
      ))}

      <Text style={styles.disclaimer}>
        This is a non-binding, informational draft estimate generated automatically from the
        project details submitted at evergreenridgetech.com. It is not a quote, offer, invoice,
        or contract. Final scope and pricing are determined only after a discovery conversation
        and a signed statement of work with Evergreen Ridge Technologies LLC.
      </Text>

      <Text style={styles.footer}>
        Generated by evergreenridgetech.com · {new Date().toLocaleString("en-US")}
      </Text>
    </Page>
  </Document>
);

export default EstimateDocument;
