import Container from "@/components/Container";
import FadeIn from "@/components/FadeIn";
import PageIntro from "@/components/PageIntro";
import React from "react";

export const metadata = {
  title: "Terms of Service",
};

const Section = ({ title, children }) => (
  <div className="mt-10">
    <h2 className="font-display text-xl font-semibold text-foreground">
      {title}
    </h2>
    <div className="mt-4 space-y-4 text-base/7 text-muted-foreground">
      {children}
    </div>
  </div>
);

const TermsOfServicePage = () => {
  return (
    <>
      <PageIntro eyebrow="Legal" title="Terms of Service">
        <p>
          These terms govern your use of this website and the services of
          Evergreen Ridge Technologies LLC (&ldquo;Evergreen Ridge
          Technology,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;). By using this site, you agree to these terms.
        </p>
      </PageIntro>

      <Container className="mt-16 sm:mt-20">
        <FadeIn>
          <div className="rounded-4xl border border-border bg-card p-8 sm:p-10">
            <p className="text-sm text-muted-foreground">
              Effective date: August 1, 2026
            </p>

            <Section title="Our services">
              <p>
                Evergreen Ridge Technology is a custom software development
                studio. We design and build web, mobile, and cloud
                applications for clients under separate, individually agreed
                statements of work or contracts. Nothing on this website
                forms a contract for services by itself.
              </p>
            </Section>

            <Section title="Cost Estimator — non-binding draft only">
              <p>
                The Cost Estimator tool on this site produces an automated,{" "}
                <strong className="text-foreground">
                  non-binding, informational draft estimate
                </strong>{" "}
                based on the project details you provide. It is generated by
                a deterministic pricing model, not a human review of your
                actual requirements, and is provided for planning purposes
                only.
              </p>
              <p>
                A draft estimate is <strong className="text-foreground">
                  not
                </strong>{" "}
                a quote, offer, invoice, or contract, and does not guarantee
                final pricing, scope, or timeline. Actual project cost and
                scope are determined only after a discovery conversation and
                a signed statement of work with us.
              </p>
            </Section>

            <Section title="Use of this website">
              <p>
                You agree to use this website only for lawful purposes, and
                not to submit false, misleading, or malicious information
                through the contact form or Cost Estimator.
              </p>
            </Section>

            <Section title="Intellectual property">
              <p>
                All content on this website — including text, graphics, the
                Evergreen Ridge Technology name and logo, and the Cost
                Estimator tool itself — is owned by Evergreen Ridge
                Technologies LLC unless otherwise noted, and may not be
                copied or reused without our written permission.
              </p>
            </Section>

            <Section title="No warranties">
              <p>
                This website and its tools, including the Cost Estimator, are
                provided &ldquo;as is&rdquo; without warranties of any kind,
                express or implied, including as to accuracy, reliability, or
                fitness for a particular purpose.
              </p>
            </Section>

            <Section title="Limitation of liability">
              <p>
                To the fullest extent permitted by law, Evergreen Ridge
                Technologies LLC is not liable for any indirect, incidental,
                or consequential damages arising from your use of this
                website or reliance on any draft estimate it produces.
              </p>
            </Section>

            <Section title="Indemnification">
              <p>
                You agree to indemnify and hold Evergreen Ridge Technologies
                LLC harmless from any claims arising out of your misuse of
                this website or violation of these terms.
              </p>
            </Section>

            <Section title="Governing law">
              <p>
                These terms are governed by applicable law without regard to
                conflict-of-law principles.{" "}
                <em>
                  A specific governing-law jurisdiction has not yet been
                  designated for this document; it will be added in a future
                  update.
                </em>
              </p>
            </Section>

            <Section title="Changes to these terms">
              <p>
                We may update these terms from time to time. Changes will be
                posted on this page with a new effective date.
              </p>
            </Section>

            <Section title="Contact us">
              <p>
                Questions about these terms? Email{" "}
                <a
                  href="mailto:contact@evergreenridgetech.com"
                  className="text-primary underline"
                >
                  contact@evergreenridgetech.com
                </a>
                .
              </p>
            </Section>
          </div>
        </FadeIn>
      </Container>
    </>
  );
};

export default TermsOfServicePage;
